import css from "./PreviewTimeline.sass?inline"
import {createElement} from "@opendaw/lib-jsx"
import {Lifecycle, isInstanceOf, Terminator} from "@opendaw/lib-std"
import {Html} from "@opendaw/lib-dom"
import {Icon} from "@/ui/components/Icon"
import {IconSymbol} from "@opendaw/studio-adapters"
import {Project} from "@opendaw/studio-core"
import {EditWrapper} from "@/ui/wrapper/EditWrapper"
import {Checkbox} from "@/ui/components/Checkbox"
import {PPQN, LoopableRegion} from "@opendaw/lib-dsp"
import {CanvasPainter} from "@/ui/canvas/painter"
import {renderNotes} from "@/ui/timeline/renderer/notes"
import {renderAudio} from "@/ui/timeline/renderer/audio"
import {TimelineRange} from "@/ui/timeline/TimelineRange"
import {Events} from "@opendaw/lib-dom"
import {InstrumentSelector} from "@/ui/timeline/tracks/audio-unit/InstrumentSelector"
import {NanoDeviceBoxAdapter} from "@opendaw/studio-adapters"

const className = Html.adoptStyleSheet(css, "PreviewTimeline")

type Construct = {
    lifecycle: Lifecycle
    project: Project
    profile: any
    service: any
}

export const PreviewTimeline = ({lifecycle, project, service}: Construct) => {
    const {engine} = project
    
    // Get sections from service (dynamically generated by LLM)
    const sections = service.preview.sections.getValue() || []
    console.log('📊 [PreviewTimeline] Loaded', sections.length, 'sections from service')
    
    // Track generation history for each track
    const trackGenerations = new Map<string, any[]>()
    const currentGenerationIndex = new Map<string, number>()
    
    // Find the smallest section length (this will be our preview standard)
    const minSectionLength = sections.length > 0
        ? Math.min(...sections.map((s: any) => s.endBar - s.startBar))
        : 16
    
    console.log('📏 [PreviewTimeline] Smallest section length:', minSectionLength, 'bars')
    
    // Calculate max bar from sections, with fallback
    const maxBar = sections.length > 0 
        ? Math.max(...sections.map((s: any) => s.endBar))
        : 16
    
    // Create a shared TimelineRange for all track visualizations
    const sharedRange = lifecycle.own(new TimelineRange())
    sharedRange.maxUnits = maxBar * PPQN.Bar
    sharedRange.showUnitInterval(0, minSectionLength * PPQN.Bar)  // Start with min length view
    
    // Section selector - always shows only minSectionLength bars from section start
    const selectSection = (startBar: number, sectionName: string) => {
        const startUnit = startBar * PPQN.Bar
        // Use minimum section length, not the full section
        const previewEndBar = startBar + minSectionLength
        const previewEndUnit = previewEndBar * PPQN.Bar
        
        console.log(`📍 Selecting section "${sectionName}": showing bars ${startBar}-${previewEndBar} (${minSectionLength} bars from section)`)
        
        // Find the section data
        const currentSection = sectionName === 'All' 
            ? null 
            : sections.find((s: any) => s.name === sectionName)
        
        console.log('🎯 Current section:', currentSection ? `${currentSection.name} with tracks: [${currentSection.tracks.join(', ')}]` : 'All (no muting)')
        
        // Update the shared range to show only minSectionLength bars
        sharedRange.showUnitInterval(startUnit, previewEndUnit)
        
        // Stop playback first
        engine.stop(false)
        
        // Set loop area, position, and mute state ALL in one modify block
        project.editing.modify(() => {
            // Set loop area to minSectionLength bars
            project.timelineBox.loopArea.from.setValue(startUnit)
            project.timelineBox.loopArea.to.setValue(previewEndUnit)
            project.timelineBox.loopArea.enabled.setValue(true)
            
            // Mute/unmute tracks based on section
            // Always show ALL tracks, but mute those not in the section
            const tracks = project.rootBoxAdapter.audioUnits.adapters()
            console.log(`🎵 Total tracks in preview: ${tracks.length}`)
            
            tracks.forEach((unit: any) => {
                const trackName = unit.input.label.unwrapOrElse(() => '')
                
                // Debug: Show regions for this track
                const track = unit.tracks.values()[0]
                if (track) {
                    const regions = track.regions.collection.asArray()
                    console.log(`  📦 Track "${trackName}" has ${regions.length} regions:`, regions.map((r: any) => `[${r.position}-${r.complete}]`).join(', '))
                }
                
                // NEVER mute Output tracks (master bus)
                if (trackName.toLowerCase().includes('output')) {
                    console.log(`  🔇 Track "${trackName}": SKIPPING (Output track, never mute)`)
                    unit.namedParameter.mute.setValue(false)
                    return
                }
                
                // For "All" section, unmute everything
                if (!currentSection) {
                    console.log(`  ✅ Track "${trackName}": UNMUTING (All section)`)
                    unit.namedParameter.mute.setValue(false)
                    return
                }
                
                // For specific sections, check if track is in the section
                const isInSection = currentSection.tracks.some((sectionTrack: string) => {
                    // Case-insensitive comparison and trim whitespace
                    return sectionTrack.trim().toLowerCase() === trackName.trim().toLowerCase()
                })
                
                const shouldBeMuted = !isInSection
                
                console.log(`  🔊 Track "${trackName}": ${shouldBeMuted ? 'MUTING' : 'UNMUTING'} (in section tracks: ${currentSection.tracks.join(', ')})`)
                
                unit.namedParameter.mute.setValue(shouldBeMuted)
            })
        })
        
        // Set position AFTER loop area is configured
        engine.setPosition(startUnit)
        
        // Re-render tracks to update visual mute indicators
        renderTracks()
        
        console.log(`✅ Section "${sectionName}" selected, showing ${minSectionLength} bars (ready to play)`)
    }
    
    // Track currently selected section for visual highlighting
    let selectedSectionName = sections.length > 0 ? sections[0].name : ''
    
    // Create section buttons dynamically from LLM-generated sections
    const sectionButtons: HTMLElement[] = []
    
    // Add buttons for each LLM-generated section - just show name
    sections.forEach((section: any) => {
        const btn = (
            <button 
                className={selectedSectionName === section.name ? 'section-btn active' : 'section-btn'}
                onclick={() => {
                    // Update selected section
                    selectedSectionName = section.name
                    
                    // Update all button states
                    sectionButtons.forEach((b, i) => {
                        if (sections[i].name === selectedSectionName) {
                            b.classList.add('active')
                        } else {
                            b.classList.remove('active')
                        }
                    })
                    
                    selectSection(section.startBar, section.name)
                }}
            >
                {section.name}
            </button>
        )
        sectionButtons.push(btn)
    })
    
    // Auto-select first section on load
    if (sections.length > 0) {
        setTimeout(() => selectSection(sections[0].startBar, sections[0].name), 100)
    }
    
    // BPM display and modification
    const bpmValueElement: HTMLElement = <span/>
    const minBpm = 40
    const maxBpm = 240
    
    const updateBpmDisplay = () => {
        const currentBpm = Math.round(project.timelineBox.bpm.getValue())
        bpmValueElement.textContent = String(currentBpm)
    }
    
    lifecycle.own(project.timelineBox.bpm.subscribe(updateBpmDisplay))
    updateBpmDisplay()
    
    const bpmDisplay: HTMLElement = (
        <div className="bpm-display">
            <div className="bpm-value">{bpmValueElement}</div>
            <div className="bpm-label">BPM</div>
        </div>
    )
    
    // Add drag-to-modify functionality (like TimeStateDisplay)
    let isDragging = false
    let dragStartY = 0
    let dragStartBpm = 0
    
    const handlePointerDown = (event: PointerEvent) => {
        isDragging = true
        dragStartY = event.clientY
        dragStartBpm = project.timelineBox.bpm.getValue()
        bpmDisplay.setPointerCapture(event.pointerId)
        bpmDisplay.classList.add('dragging')
        event.preventDefault()
    }
    
    const handlePointerMove = (event: PointerEvent) => {
        if (!isDragging) return
        
        const deltaY = dragStartY - event.clientY
        const newBpm = Math.max(minBpm, Math.min(maxBpm, dragStartBpm + deltaY))
        
        project.editing.modify(() => {
            project.timelineBox.bpm.setValue(newBpm)
        }, false)
        
        event.preventDefault()
    }
    
    const handlePointerUp = (event: PointerEvent) => {
        if (!isDragging) return
        
        isDragging = false
        bpmDisplay.releasePointerCapture(event.pointerId)
        bpmDisplay.classList.remove('dragging')
        project.editing.mark()
        event.preventDefault()
    }
    
    bpmDisplay.addEventListener('pointerdown', handlePointerDown)
    bpmDisplay.addEventListener('pointermove', handlePointerMove)
    bpmDisplay.addEventListener('pointerup', handlePointerUp)
    bpmDisplay.addEventListener('pointercancel', handlePointerUp)
    
    lifecycle.own({
        terminate: () => {
            bpmDisplay.removeEventListener('pointerdown', handlePointerDown)
            bpmDisplay.removeEventListener('pointermove', handlePointerMove)
            bpmDisplay.removeEventListener('pointerup', handlePointerUp)
            bpmDisplay.removeEventListener('pointercancel', handlePointerUp)
        }
    })
    
    // Playback control: play or stop+restart
    const playButtonElement: HTMLButtonElement = <button className="play-btn" onclick={() => {
        if (engine.isPlaying.getValue()) {
            // Stop and restart from beginning
            engine.stop(false)
            engine.setPosition(project.timelineBox.loopArea.from.getValue())
        } else {
            engine.play()
        }
    }}/>
    
    // Update play/pause button
    const updatePlayButton = () => {
        Html.empty(playButtonElement)
        if (engine.isPlaying.getValue()) {
            playButtonElement.appendChild(<Icon symbol={IconSymbol.Stop}/>)
        } else {
            playButtonElement.appendChild(<Icon symbol={IconSymbol.Play}/>)
        }
    }
    
    lifecycle.own(engine.isPlaying.subscribe(updatePlayButton))
    updatePlayButton()
    
    // Tracks visualization
    const tracksElement: HTMLElement = <div className="preview-tracks"/>
    const renderTracks = () => {
        Html.empty(tracksElement)
        
        const tracks = project.rootBoxAdapter.audioUnits.adapters()
        
        // Filter out Output tracks from preview
        const filteredTracks = tracks.filter((unit: any) => {
            const trackName = unit.input.label.unwrapOrElse(() => '')
            return !trackName.toLowerCase().includes('output')
        })
        
        if (filteredTracks.length === 0) {
            tracksElement.appendChild(
                <div className="no-tracks">
                    <span>No tracks yet - waiting for AI generation...</span>
                </div>
            )
            return
        }
        
        filteredTracks.forEach((unit, index) => {
            const trackName = unit.input.label.unwrapOrElse(() => `Track ${index + 1}`)
            const {mute, solo} = unit.namedParameter
            
            // Initialize generation history for this track if not exists
            if (!trackGenerations.has(trackName)) {
                trackGenerations.set(trackName, [{
                    type: 'original',
                    data: unit,
                    timestamp: Date.now()
                }])
                currentGenerationIndex.set(trackName, 0)
            }
            
            // Get actual device type
            const inputAdapter = unit.inputAdapter.unwrapOrNull()
            let icon = IconSymbol.Waveform
            let trackType = 'Unknown'
            
            if (inputAdapter) {
                const deviceType = inputAdapter.constructor.name
                if (deviceType.includes('Nano') || deviceType.includes('Sampler')) {
                    icon = IconSymbol.Piano
                    trackType = 'MIDI'
                } else if (deviceType.includes('AudioPlayer') || deviceType.includes('Tape')) {
                    icon = IconSymbol.Waveform  
                    trackType = 'Audio'
                } else {
                    icon = IconSymbol.Waveform
                    trackType = deviceType.replace('DeviceBoxAdapter', '')
                }
            }
            
            // Mute/solo controls
            const muteModel = EditWrapper.forAutomatableParameter(project.editing, mute)
            const soloModel = EditWrapper.forAutomatableParameter(project.editing, solo)
            
            // Subscribe to manual mute changes to update sections
            lifecycle.own(mute.subscribe((muteAdapter) => {
                const isMuted = muteAdapter.getValue()
                
                // Only update sections if we're NOT in "All" mode
                if (selectedSectionName !== 'All') {
                    const currentSections = service.preview.sections.getValue()
                    const updatedSections = currentSections.map((section: any) => {
                        if (section.name === selectedSectionName) {
                            // Track is being manually toggled in this section
                            const trackIndex = section.tracks.findIndex((t: string) => 
                                t.trim().toLowerCase() === trackName.trim().toLowerCase()
                            )
                            
                            if (isMuted && trackIndex !== -1) {
                                // Remove track from section when muted
                                console.log(`🔇 [SECTION-UPDATE] Removing "${trackName}" from section "${section.name}"`)
                                return {
                                    ...section,
                                    tracks: section.tracks.filter((t: string) => 
                                        t.trim().toLowerCase() !== trackName.trim().toLowerCase()
                                    )
                                }
                            } else if (!isMuted && trackIndex === -1) {
                                // Add track to section when unmuted
                                console.log(`🔊 [SECTION-UPDATE] Adding "${trackName}" to section "${section.name}"`)
                                return {
                                    ...section,
                                    tracks: [...section.tracks, trackName]
                                }
                            }
                        }
                        return section
                    })
                    
                    // Update the sections
                    service.preview.sections.setValue(updatedSections)
                    console.log(`✅ [SECTION-UPDATE] Updated sections:`, updatedSections)
                }
            }))
            
            const muteBtn = (
                <Checkbox 
                    lifecycle={lifecycle}
                    model={muteModel}
                    className="mute-btn"
                    appearance={{activeColor: '#ff6b6b', framed: true}}>
                    M
                </Checkbox>
            )
            
            const soloBtn = (
                <Checkbox 
                    lifecycle={lifecycle}
                    model={soloModel}
                    className="solo-btn"
                    appearance={{activeColor: '#ffd93d', framed: true}}>
                    S
                </Checkbox>
            )
            
            // Track-specific play/pause button with auto-solo
            let trackIsPlaying = false
            let wasSoloEnabled = false
            const trackPlayBtn = (
                <button 
                    className="track-play-btn"
                    onclick={async () => {
                        if (!trackIsPlaying) {
                            // Start playing with solo
                            console.log(`▶️ Playing track "${trackName}" with solo`)
                            
                            // Remember if solo was already enabled
                            wasSoloEnabled = solo.getValue()
                            
                            // Enable solo for this track
                            project.editing.modify(() => {
                                solo.setValue(true)
                            })
                            
                            // Start playback if not already playing
                            if (!engine.isPlaying.getValue()) {
                                engine.play()
                            }
                            
                            trackIsPlaying = true
                            trackPlayBtn.classList.add('playing')
                            trackPlayBtn.textContent = '⏸'
                            trackPlayBtn.title = `Pause "${trackName}"`
                        } else {
                            // Stop playing and restore solo state
                            console.log(`⏸ Pausing track "${trackName}" and restoring solo state`)
                            
                            // Restore original solo state
                            project.editing.modify(() => {
                                solo.setValue(wasSoloEnabled)
                            })
                            
                            // Stop playback
                            engine.stop(false)
                            
                            trackIsPlaying = false
                            trackPlayBtn.classList.remove('playing')
                            trackPlayBtn.textContent = '▶'
                            trackPlayBtn.title = `Play "${trackName}" solo`
                        }
                    }}
                    title={`Play "${trackName}" solo`}
                >
                    ▶
                </button>
            )
            
            // Sync with global playback state
            lifecycle.own(engine.isPlaying.subscribe((observableValue) => {
                const playing = observableValue.getValue()
                if (!playing && trackIsPlaying) {
                    // Global playback stopped, reset track play button
                    trackIsPlaying = false
                    trackPlayBtn.classList.remove('playing')
                    trackPlayBtn.textContent = '▶'
                    trackPlayBtn.title = `Play "${trackName}" solo`
                    
                    // Restore solo state
                    project.editing.modify(() => {
                        solo.setValue(wasSoloEnabled)
                    })
                }
            }))
            
            // Create enhanced retry interface with navigation and toggle
            const instrumentLifecycle = lifecycle.own(new Terminator())
            let instrumentSelectorElement: HTMLElement | null = null
            let retryButtonElement: HTMLElement | null = null
            let retryInputElement: HTMLElement | null = null
            let isRetrying = false
            let retryLoadingOverlay: HTMLElement | null = null
            
            // Get current generation info and initialize if empty
            let generations = trackGenerations.get(trackName) || []
            
            // Initialize with current track as first generation if empty
            if (generations.length === 0) {
                const initialGeneration = {
                    type: trackType,
                    data: unit,
                    timestamp: Date.now(),
                    description: '',
                    audioUnit: unit,
                    trackType: trackType
                }
                generations = [initialGeneration]
                trackGenerations.set(trackName, generations)
                currentGenerationIndex.set(trackName, 0)
                console.log(`🎵 Initialized first generation for ${trackName} (${trackType})`)
            }
            
            // Navigation functions removed for now
            
            // Navigation buttons removed for now
            
            // Create a sliding toggle for MIDI/Audio
            let isAudioMode = false
            const toggleContainer = <div className="sliding-toggle"/>
            const descriptionInput = <input 
                type="text" 
                className="retry-input" 
                placeholder="Describe the audio you want..."
                title="Describe the audio you want"
            />
            
            // Initialize the sliding toggle
            toggleContainer.innerHTML = `
                <div class="toggle-track">
                    <div class="toggle-slider"></div>
                    <button class="toggle-option" data-mode="midi">MIDI</button>
                    <button class="toggle-option" data-mode="audio">Audio</button>
                </div>
            `
            
            // Update toggle state
            const updateToggleState = () => {
                const slider = toggleContainer.querySelector('.toggle-slider') as HTMLElement
                const midiBtn = toggleContainer.querySelector('[data-mode="midi"]') as HTMLElement
                const audioBtn = toggleContainer.querySelector('[data-mode="audio"]') as HTMLElement
                
                if (slider && midiBtn && audioBtn) {
                    if (isAudioMode) {
                        slider.style.transform = 'translateX(100%)'
                        midiBtn.classList.remove('active')
                        audioBtn.classList.add('active')
                    } else {
                        slider.style.transform = 'translateX(0)'
                        midiBtn.classList.add('active')
                        audioBtn.classList.remove('active')
                    }
                }
                
                // Update input state instead of hiding it
                if (isAudioMode) {
                    descriptionInput.disabled = false
                    descriptionInput.style.opacity = '1'
                    descriptionInput.style.cursor = 'text'
                    descriptionInput.placeholder = 'Describe the audio you want...'
                } else {
                    descriptionInput.disabled = true
                    descriptionInput.style.opacity = '0.5'
                    descriptionInput.style.cursor = 'not-allowed'
                    descriptionInput.placeholder = 'Switch to Audio mode to describe...'
                }
            }
            
            // Add click handlers
            toggleContainer.addEventListener('click', (e: Event) => {
                const target = e.target as HTMLElement
                if (target.dataset.mode) {
                    isAudioMode = target.dataset.mode === 'audio'
                    updateToggleState()
                    console.log(`🎵 Switched to ${isAudioMode ? 'Audio' : 'MIDI'} mode`)
                }
            })
            
            // Initial state
            updateToggleState()
            
            
            // Refresh button
            const refreshBtn = (
                <button 
                    className="refresh-btn"
                    onclick={async () => {
                        if (isRetrying) return
                        
                        const projectId = service.preview.originalProjectId
                        if (!projectId) {
                            console.error('❌ No project ID found')
                            return
                        }
                        
                        try {
                            isRetrying = true
                            refreshBtn.classList.add('loading')
                            if (retryLoadingOverlay) {
                                retryLoadingOverlay.style.display = 'flex'
                            }
                            
                            if (isAudioMode) {
                                const customDescription = (descriptionInput as HTMLInputElement).value.trim()
                                await service.retryMelodyWithAudio(trackName, projectId, project, unit, customDescription)
                                
                                // Add new audio generation to history
                                const newGeneration = {
                                    type: 'Audio',
                                    data: unit,
                                    timestamp: Date.now(),
                                    description: customDescription,
                                    audioUnit: unit,
                                    trackType: 'Audio'
                                }
                                generations.push(newGeneration)
                                currentGenerationIndex.set(trackName, generations.length - 1)
                                trackGenerations.set(trackName, generations)
                                console.log(`🎵 Added audio generation ${generations.length - 1} for ${trackName}`)
                                
                                // Navigation buttons removed for now
                            } else {
                                await service.retryMelody(trackName, projectId, project, unit)
                                
                                // Add new MIDI generation to history
                                const newGeneration = {
                                    type: 'MIDI',
                                    data: unit,
                                    timestamp: Date.now(),
                                    description: '',
                                    audioUnit: unit,
                                    trackType: 'MIDI'
                                }
                                generations.push(newGeneration)
                                currentGenerationIndex.set(trackName, generations.length - 1)
                                trackGenerations.set(trackName, generations)
                                console.log(`🎹 Added MIDI generation ${generations.length - 1} for ${trackName}`)
                                
                                // Navigation buttons removed for now
                            }
                        } catch (error) {
                            console.error('❌ Retry failed:', error)
                        } finally {
                            isRetrying = false
                            refreshBtn.classList.remove('loading')
                            if (retryLoadingOverlay) {
                                retryLoadingOverlay.style.display = 'none'
                            }
                        }
                    }}
                    title="Refresh"
                >
                    ↻
                </button>
            )
            
            // Create complete retry section
            const retrySection = (
                <div className="track-retry-section">
                    <div className="retry-container">
                        <div className="retry-controls">
                            {toggleContainer}
                            <div className="retry-input-wrapper">
                                {descriptionInput}
                            </div>
                        </div>
                        <div className="retry-action">
                            <span className="retry-label">Regenerate</span>
                            {refreshBtn}
                        </div>
                    </div>
                </div>
            )
            
            // Add instrument selector for MIDI tracks
            if (inputAdapter && isInstanceOf(inputAdapter, NanoDeviceBoxAdapter)) {
                const previewServiceWrapper = {
                    ...service,
                    get project() { return project },
                    get profile() { return service.preview.profile.getValue()! },
                    get hasProfile() { return service.preview.profile.getValue() !== null }
                } as any
                
                instrumentSelectorElement = (
                    <InstrumentSelector 
                        lifecycle={instrumentLifecycle}
                        service={previewServiceWrapper}
                        adapter={inputAdapter}
                    />
                )
            }
            
            retryInputElement = descriptionInput
            retryButtonElement = retrySection
            
            // Create track visualization
            const contentViz = createTrackVisualization(lifecycle, unit)
            
            const isMuted = mute.getValue()
            
            // Create muted text overlay (will be updated reactively)
            const mutedOverlay = <div className="muted-overlay" style="display: none;">
                <div className="muted-text-container">
                    <span className="muted-text">
                        Not played in {selectedSectionName}
                    </span>
                    <span className="muted-subtext">
                        Unmute to play
                    </span>
                </div>
            </div>
            
            // Function to update muted overlay visibility
            const updateMutedOverlay = () => {
                const currentSection = selectedSectionName === 'All' 
                    ? null 
                    : sections.find((s: any) => s.name === selectedSectionName)
                
                const shouldShow = mute.getValue() && currentSection
                mutedOverlay.style.display = shouldShow ? 'flex' : 'none'
                
                if (shouldShow) {
                    const textElement = mutedOverlay.querySelector('.muted-text') as HTMLElement
                    if (textElement) {
                        textElement.textContent = `Not played in ${currentSection.name}`
                    }
                }
            }
            
            // Initial update
            updateMutedOverlay()
            
            // Subscribe to mute changes
            lifecycle.own(mute.subscribe(() => {
                updateMutedOverlay()
            }))
            
            // Loading overlay for retry
            if (!retryLoadingOverlay) {
                retryLoadingOverlay = (
                    <div className="retry-loading-overlay" style="display: none;">
                        <div className="retry-spinner"></div>
                        <span>Regenerating...</span>
                    </div>
                )
            }
            
            const trackElement: HTMLElement = (
                <div className={isMuted ? 'track-row muted' : 'track-row'}>
                    <div className="track-header">
                        <div className="track-info">
                            <Icon symbol={icon}/>
                            <span className="track-name">{trackName}</span>
                        </div>
                        {instrumentSelectorElement ? (
                            <div className="track-instrument">
                                {instrumentSelectorElement}
                            </div>
                        ) : null}
                        <div className="track-controls">
                            {trackPlayBtn}
                            {muteBtn}
                            {soloBtn}
                        </div>
                    </div>
                    <div className="track-content">
                        {contentViz}
                        {retryLoadingOverlay}
                        {mutedOverlay}
                    </div>
                    {retryInputElement || retryButtonElement ? (
                        <div className="track-retry-section">
                            <div className="retry-container">
                                {retryInputElement ? (
                                    <div className="retry-input-wrapper">
                                        <span className="retry-label">Custom prompt:</span>
                                        {retryInputElement}
                                    </div>
                                ) : null}
                                {retryButtonElement}
                            </div>
                        </div>
                    ) : null}
                </div>
            )
            
            lifecycle.own(mute.subscribe((muteAdapter) => {
                const isMuted = muteAdapter.getValue()
                trackElement.className = isMuted ? 'track-row muted' : 'track-row'
            }))
            
            tracksElement.appendChild(trackElement)
        })
    }
    
    // Create track visualization with real timeline rendering
    const createTrackVisualization = (lifecycle: Lifecycle, unit: any): HTMLElement => {
        const container: HTMLElement = <div className="track-canvas-container"/>
        const canvas: HTMLCanvasElement = <canvas className="track-canvas"/>
        container.appendChild(canvas)
        
        // Function to update canvas size to match container
        const updateCanvasSize = () => {
            const containerWidth = container.clientWidth
            const cssHeight = 80
            
            canvas.width = containerWidth * devicePixelRatio
            canvas.height = cssHeight * devicePixelRatio
            canvas.style.width = `${containerWidth}px`
            canvas.style.height = `${cssHeight}px`
            
            // Update shared range width
            sharedRange.width = containerWidth
            
            // Re-render
            painter.requestUpdate()
        }
        
        const ctx = canvas.getContext('2d')
        if (!ctx) return container
        
        const painter = lifecycle.own(new CanvasPainter(canvas, ({context}: {context: CanvasRenderingContext2D}) => {
            const {width, height} = canvas
            
            // Clear background
            context.clearRect(0, 0, width, height)
            context.fillStyle = '#0a0a0a'
            context.fillRect(0, 0, width, height)
            
            // Draw grid based on visible range
            const numBars = Math.ceil((sharedRange.unitMax - sharedRange.unitMin) / PPQN.Bar)
            context.strokeStyle = '#222'
            context.lineWidth = 1
            for (let i = 0; i <= numBars; i++) {
                const x = (i / numBars) * width
                context.beginPath()
                context.moveTo(x, 0)
                context.lineTo(x, height)
                context.stroke()
            }
            
            // Draw playback cursor (white line)
            const position = engine.position.getValue()
            if (position >= sharedRange.unitMin && position <= sharedRange.unitMax) {
                const cursorX = sharedRange.unitToX(position) * devicePixelRatio
                context.strokeStyle = '#fff'
                context.lineWidth = 2 * devicePixelRatio
                context.beginPath()
                context.moveTo(cursorX, 0)
                context.lineTo(cursorX, height)
                context.stroke()
            }
            
            // Get track and regions
            const track = unit.tracks.values()[0]
            if (!track) return
            
            const regions = track.regions.collection.asArray()
            if (regions.length === 0) return
            
            const bound = {top: 10 * devicePixelRatio, bottom: height - 10 * devicePixelRatio}
            
            // Render each region using the EXACT same rendering as main timeline
            regions.forEach((region: any) => {
                const position = region.position
                const complete = region.complete
                
                // Get color from region hue (like main timeline)
                const hue = region.hue || 0
                const saturation = region.mute ? 5 : 60  // Desaturate if muted
                const contentColor = `hsl(${hue}, ${saturation}%, 45%)`
                const colors = {contentColor}
                
                // Use the visitor pattern to render based on region type (EXACTLY like RegionRenderer.ts)
                region.accept({
                    visitNoteRegionBoxAdapter: (noteRegion: any) => {
                        if (!noteRegion.hasCollection) return
                        
                        for (const pass of LoopableRegion.locateLoops({
                            position,
                            complete,
                            loopOffset: 0,
                            loopDuration: complete - position
                        }, sharedRange.unitMin, sharedRange.unitMax)) {
                            renderNotes(context, sharedRange, noteRegion, bound, colors, pass)
                        }
                    },
                    visitAudioRegionBoxAdapter: (audioRegion: any) => {
                        // Use actual audio region loop parameters for correct alignment
                        const audioLoopOffset = audioRegion.loopOffset || 0
                        const audioLoopDuration = audioRegion.loopDuration || (complete - position)
                        
                        for (const pass of LoopableRegion.locateLoops({
                            position,
                            complete,
                            loopOffset: audioLoopOffset,
                            loopDuration: audioLoopDuration
                        }, sharedRange.unitMin, sharedRange.unitMax)) {
                            renderAudio(context, sharedRange, audioRegion.file, audioRegion.gain, bound, colors, pass)
                        }
                    },
                    visitValueRegionBoxAdapter: () => {
                        // Skip value regions
                    }
                })
            })
        }))
        
        // Subscribe to position changes to update cursor
        lifecycle.own(engine.position.subscribe(() => painter.requestUpdate()))
        
        // Subscribe to range changes (when section is selected)
        lifecycle.own(sharedRange.subscribe(() => painter.requestUpdate()))
        
        // Subscribe to region changes
        const track = unit.tracks.values()[0]
        if (track) {
            lifecycle.own(track.regions.subscribeChanges(() => painter.requestUpdate()))
        }
        
        // Add double-click to edit regions (like main timeline)
        lifecycle.own(Events.subscribe(canvas, 'dblclick', (event: MouseEvent) => {
            console.log('🖱️ Double-click detected on canvas!')
            if (!track) {
                console.log('  ⚠️ No track available')
                return
            }
            
            const rect = canvas.getBoundingClientRect()
            const x = event.clientX - rect.left
            
            console.log('  📍 Click X:', x, 'Canvas width:', canvas.clientWidth)
            
            // Use shared range to convert x to units
            const clickedUnit = sharedRange.xToUnit(x)
            console.log('  📏 Clicked at unit:', clickedUnit)
            
            const clickedRegion = track.regions.collection.lowerEqual(clickedUnit)
            console.log('  🎯 Found region:', clickedRegion ? clickedRegion.label : 'null')
            
            if (clickedRegion) {
                console.log('  ✅ Region found! Position:', clickedRegion.position, 'Complete:', clickedRegion.complete)
                console.log('  🔍 Clicked unit:', clickedUnit, '< Complete?', clickedUnit < clickedRegion.complete)
            }
            
            if (clickedRegion && clickedUnit < clickedRegion.complete) {
                console.log('  ✨ Opening content editor for:', clickedRegion.label)
                
                // Open editor in preview context
                console.log('    🎹 Opening editor in preview...')
                project.editing.modify(() => {
                    project.userEditingManager.timeline.edit(clickedRegion.box)
                    // Signal that we want the editor to show in a modal
                    service.preview.editingRegion.setValue(clickedRegion)
                })
                console.log('  ✅ Editor should appear in preview!')
            } else {
                console.log('  ❌ No valid region at this position')
            }
        }))
        
        painter.requestUpdate()
        
        // Initial size update
        setTimeout(() => updateCanvasSize(), 0)
        
        // Watch for container size changes
        const resizeObserver = new ResizeObserver(() => {
            updateCanvasSize()
        })
        resizeObserver.observe(container)
        lifecycle.own({terminate: () => resizeObserver.disconnect()})
        
        return container
    }
    
    renderTracks()
    
    // Subscribe to audio units changes
    lifecycle.own(project.rootBoxAdapter.audioUnits.catchupAndSubscribe({
        onAdd: () => {
            console.log('🔄 [PreviewTimeline] Audio unit added, re-rendering tracks')
            renderTracks()
        },
        onRemove: () => {
            console.log('🔄 [PreviewTimeline] Audio unit removed, re-rendering tracks')
            renderTracks()
        },
        onReorder: () => {
            console.log('🔄 [PreviewTimeline] Audio units reordered, re-rendering tracks')
            renderTracks()
        }
    }))
    
    // Create container with ONLY tracks (no headers, no controls)
    const container = (
        <div className={className}>
            {tracksElement}
        </div>
    )
    
    // Return container + controls for parent to position
    return {
        element: container,
        playButton: playButtonElement,
        bpmDisplay: bpmDisplay,
        sectionButtons: sectionButtons
    }
}
